pipeline:
  name: Build utils_tools
  identifier: Build_utils_tools_1775033381692
  projectIdentifier: Demo
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
              - step:
                  type: Run
                  name: Show Git Version
                  identifier: Show_Git_Version
                  spec:
                    shell: Sh
                    command: git --version
                contextType: Pipeline
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: Posdelangithub
                    repoName: util_tools.git
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Sh
                    command: ls -al
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: Posdelangithub
        repoName: utils_tools
        build: <+input>
  variables:
    - name: projectId
      type: String
      description: ""
      required: true
      value: ""
  notificationRules:
    - name: success
      identifier: success
      pipelineEvents:
        - type: AllEvents
      notificationMethod:
        type: Email
        spec:
          userGroups: []
          recipients:
            - posdelan@gmail.com
      enabled: true
